Repository windsorcli/core, pull requests merged in 2024-12, with the labels that each got.

#10 Add aqua proj
  .github/renovate.json
  .tool-versions
  aqua.yaml
Labels: chore

#9 Add Checkers
  .github/workflows/ci.yaml
  .gitignore
  .yamllint
  aqua.yaml
  contexts/local/blueprint.yaml
  contexts/local/compose.yaml
  contexts/local/terraform/cluster/talos.tfvars
  terraform/cluster/talos/main.tf
  terraform/cluster/talos/modules/machine/main.tf
  terraform/cluster/talos/modules/machine/variables.tf
  terraform/cluster/talos/variables.tf
Labels: chore

#17 Renovate upates
  .github/renovate.json
Labels: chore

#20 renovate fix
  .github/renovate.json
Labels: dependencies

#29 Renovate 7
  .github/renovate.json
  contexts/local/Corefile
  contexts/local/blueprint.yaml
  contexts/local/compose.yaml
  contexts/local/terraform/cluster/talos.tfvars
Labels: chore

#32 Fix json file
  .github/renovate.json
Labels: chore

#42 Add gitops/flux component
  .gitignore
  contexts/local/Corefile
  contexts/local/blueprint.yaml
  contexts/local/compose.yaml
  contexts/local/terraform/cluster/talos.tfvars
  contexts/local/terraform/gitops/flux.tfvars
  terraform/cluster/talos/.terraform.lock.hcl
  terraform/cluster/talos/main.tf
  terraform/cluster/talos/modules/machine/main.tf
  terraform/gitops/flux/.terraform.lock.hcl
  terraform/gitops/flux/main.tf
  terraform/gitops/flux/variables.tf
Labels: feature
