Repository windsorcli/core, pull requests merged in 2025-07, with the labels that each got.

#257 Fluentbit support
  contexts/local/blueprint.yaml
  kustomize/telemetry/base/fluentbit/git-repository.yaml
  kustomize/telemetry/base/fluentbit/helm-release.yaml
  kustomize/telemetry/base/fluentbit/helm-repository.yaml
  kustomize/telemetry/base/fluentbit/kustomization.yaml
  kustomize/telemetry/base/fluentbit/prometheus/kustomization.yaml
  kustomize/telemetry/base/fluentbit/prometheus/patches/helm-release.yaml
  kustomize/telemetry/resources/fluentbit/containerd/configmap.yaml
  kustomize/telemetry/resources/fluentbit/containerd/fluentbit-clusterfilter.yaml
  kustomize/telemetry/resources/fluentbit/containerd/fluentbit-clusterinput.yaml
  kustomize/telemetry/resources/fluentbit/containerd/kustomization.yaml
  kustomize/telemetry/resources/fluentbit/fluentbit.yaml
  kustomize/telemetry/resources/fluentbit/fluentd/clusteroutput.yaml
  kustomize/telemetry/resources/fluentbit/fluentd/kustomization.yaml
  kustomize/telemetry/resources/fluentbit/kubernetes/fluentbit-clusterfilter.yaml
  kustomize/telemetry/resources/fluentbit/kubernetes/fluentbit-clusterinput.yaml
  kustomize/telemetry/resources/fluentbit/kubernetes/kustomization.yaml
  kustomize/telemetry/resources/fluentbit/kustomization.yaml
  kustomize/telemetry/resources/fluentbit/systemd/configmap.yaml
  kustomize/telemetry/resources/fluentbit/systemd/fluentbit-clusterfilter.yaml
  kustomize/telemetry/resources/fluentbit/systemd/kustomization.yaml
  terraform/gitops/flux/.terraform.lock.hcl
  terraform/gitops/flux/main.tf
Labels: feature

#681 chore(docs): Update latest docs
  terraform/backend/azurerm/README.md
  terraform/backend/s3/README.md
  terraform/cluster/aws-eks/README.md
  terraform/cluster/aws-eks/additions/README.md
  terraform/cluster/azure-aks/README.md
  terraform/cluster/talos/README.md
  terraform/gitops/flux/README.md
  terraform/network/aws-vpc/README.md
  terraform/network/azure-vnet/README.md
Labels: documentation, chore

#682 feature(template): Create initial core template blueprint
  contexts/.gitignore
  contexts/_template/blueprint.jsonnet
  contexts/_template/terraform/cluster/aws-eks.jsonnet
  contexts/_template/terraform/cluster/azure-aks.jsonnet
  contexts/_template/terraform/cluster/talos.jsonnet
  contexts/_template/terraform/network/aws-vpc.jsonnet
  contexts/_template/terraform/network/azure-vnet.jsonnet
  contexts/aws-example/blueprint.yaml
  contexts/aws-example/terraform/cluster/aws-eks.tfvars
  contexts/aws-example/terraform/cluster/aws-eks/additions.tfvars
  contexts/aws-example/terraform/gitops/flux.tfvars
  contexts/aws-example/terraform/network/aws-vpc.tfvars
  contexts/azure-example/blueprint.yaml
  contexts/azure-example/terraform/backend/azurerm.tfvars
  contexts/azure-example/terraform/cluster/azure-aks.tfvars
  contexts/azure-example/terraform/gitops/flux.tfvars
  contexts/azure-example/terraform/network/azure-vnet.tfvars
  contexts/local/blueprint.yaml
  contexts/local/terraform/cluster/talos.tfvars
  contexts/local/terraform/gitops/flux.tfvars
  windsor.yaml
Labels: feature

#684 ci(publish): Publishes core as an oci artifact
  .github/workflows/ci.yaml
Labels: chore

#702 feat(observability): Add fluentd support
  contexts/_template/blueprint.jsonnet
  kustomize/observability/base/kustomization.yaml
  kustomize/observability/base/namespace.yaml
  kustomize/observability/fluentd/fluentd.yaml
  kustomize/observability/fluentd/helm-release.yaml
  kustomize/observability/fluentd/kustomization.yaml
  kustomize/observability/fluentd/stdout/clusteroutput.yaml
  kustomize/observability/fluentd/stdout/kustomization.yaml
Labels: feature

#714 fix(template): Exclude backend from default config
  contexts/_template/blueprint.jsonnet
Labels: bug

#711 ci(publish): Publish "latest" tag from main
  .github/workflows/ci.yaml
Labels: chore

#717 feat(csi): Set a default storage class on AWS
  contexts/_template/blueprint.jsonnet
  kustomize/csi/aws-ebs/default-storageclass.yaml
  kustomize/csi/aws-ebs/kustomization.yaml
Labels: feature
