Repository windsorcli/core, pull requests merged in 2025-05, with the labels that each got.

#376 Adds AKS support
  terraform/cluster/azure-aks/.terraform.lock.hcl
  terraform/cluster/azure-aks/main.tf
  terraform/cluster/azure-aks/outputs.tf
  terraform/cluster/azure-aks/variables.tf
  terraform/network/azure-vnet/.terraform.lock.hcl
  terraform/network/azure-vnet/main.tf
  terraform/network/azure-vnet/outputs.tf
  terraform/network/azure-vnet/variables.tf
Labels: feature

#403 Enable patching of private issuer configmap
  kustomize/pki/resources/private-issuer/ca/rbac.yaml
Labels: bug

#256 Minio support
  contexts/local/blueprint.yaml
  kustomize/object-store/base/kustomization.yaml
  kustomize/object-store/base/minio/git-repository.yaml
  kustomize/object-store/base/minio/helm-release.yaml
  kustomize/object-store/base/minio/helm-repository.yaml
  kustomize/object-store/base/minio/kustomization.yaml
  kustomize/object-store/base/namespace.yaml
  kustomize/object-store/kustomization.yaml
  kustomize/object-store/resources/common/certificate.yaml
  kustomize/object-store/resources/common/job.yaml
  kustomize/object-store/resources/common/kustomization.yaml
  kustomize/object-store/resources/common/rbac.yaml
  kustomize/object-store/resources/common/tenant.yaml
  kustomize/object-store/resources/kustomization.yaml
Labels: feature

#241 Add S3 terraform backend
  .github/workflows/ci.yaml
  .gitignore
  Taskfile.yaml
  contexts/.gitignore
  contexts/local/blueprint.yaml
  terraform/backend/s3/.terraform.lock.hcl
  terraform/backend/s3/main.tf
  terraform/backend/s3/outputs.tf
  terraform/backend/s3/variables.tf
Labels: feature

#424 Fixes Azure aks module key issues
  terraform/cluster/azure-aks/.terraform.lock.hcl
  terraform/cluster/azure-aks/main.tf
  terraform/cluster/azure-aks/variables.tf
Labels: bug

#425 Fixes resource dependency on aks module
  terraform/cluster/azure-aks/main.tf
Labels: bug

#426 Adds AKS role contributor
  terraform/cluster/azure-aks/main.tf
Labels: feature

#430 Revert "Adds AKS role contributor"
  terraform/cluster/azure-aks/main.tf
Labels: bug

#429 Terraform unit tests
  .cursorrules
  .github/workflows/ci.yaml
  .gitignore
  Taskfile.yaml
  terraform/STYLE.md
  terraform/backend/azurerm/main.tf
  terraform/backend/azurerm/test.tftest.hcl
  terraform/backend/s3/main.tf
  terraform/backend/s3/templates/backend.tftpl
  terraform/backend/s3/test.tftest.hcl
  terraform/backend/s3/variables.tf
  terraform/cluster/azure-aks/main.tf
  terraform/cluster/azure-aks/test.tftest.hcl
  terraform/cluster/talos/main.tf
  terraform/cluster/talos/modules/machine/.terraform.lock.hcl
  terraform/cluster/talos/modules/machine/test.tftest.hcl
  terraform/cluster/talos/test.tftest.hcl
  terraform/gitops/flux/test.tftest.hcl
  terraform/network/azure-vnet/test.tftest.hcl
Labels: chore

#432 Terraform docs
  .github/release-drafter.yml
  .github/workflows/enforce-pr-labels.yaml
  .github/workflows/terraform-docs.yml
  Taskfile.yaml
  docs/terraform/backend/azurerm/azurerm.md
  docs/terraform/backend/s3/s3.md
  docs/terraform/cluster/azure-aks/azure-aks.md
  docs/terraform/cluster/talos/modules/machine/machine.md
  docs/terraform/cluster/talos/talos.md
  docs/terraform/gitops/flux/flux.md
  docs/terraform/network/azure-vnet/azure-vnet.md
  terraform/.terraform-docs.yml
Labels: documentation, chore

#438 Fixes AKS pvc attachment issues
  docs/terraform/cluster/azure-aks.md
  terraform/cluster/azure-aks/main.tf
Labels: bug

#441 Remove automatic doc generation
  .github/workflows/ci.yaml
  .vscode/settings.json
Labels: chore

#372 Add AWS EKS Support
  .gitignore
  contexts/aws-example/blueprint.yaml
  contexts/aws-example/terraform/cluster/aws-eks.tfvars
  contexts/aws-example/terraform/gitops/flux.tfvars
  contexts/aws-example/terraform/network/aws-vpc.tfvars
  terraform/cluster/aws-eks/.terraform.lock.hcl
  terraform/cluster/aws-eks/main.tf
  terraform/cluster/aws-eks/outputs.tf
  terraform/cluster/aws-eks/templates/kubeconfig.tpl
  terraform/cluster/aws-eks/variables.tf
  terraform/network/aws-vpc/.terraform.lock.hcl
  terraform/network/aws-vpc/main.tf
  terraform/network/aws-vpc/outputs.tf
  terraform/network/aws-vpc/variables.tf
  windsor.yaml
Labels: feature

#442 Azure resource renaming
  terraform/cluster/azure-aks/main.tf
  terraform/cluster/azure-aks/test.tftest.hcl
  terraform/cluster/azure-aks/variables.tf
  terraform/network/azure-vnet/main.tf
  terraform/network/azure-vnet/outputs.tf
  terraform/network/azure-vnet/test.tftest.hcl
  terraform/network/azure-vnet/variables.tf
Labels: chore

#444 AWS: Initial TF Testfiles && fix RT assn
  terraform/cluster/aws-eks/main.tf
  terraform/cluster/aws-eks/test.tftest.hcl
  terraform/cluster/aws-eks/variables.tf
  terraform/network/aws-vpc/main.tf
  terraform/network/aws-vpc/test.tftest.hcl
Labels: enhancement

#455 Code consistency tools
  .github/workflows/ci.yaml
  README.md
  Taskfile.yaml
  aqua.yaml
  docs/terraform/cluster/aws-eks.md
  docs/terraform/cluster/azure-aks.md
  docs/terraform/cluster/talos.md
  docs/terraform/network/aws-vpc.md
  docs/terraform/network/azure-vnet.md
  lefthook.yml
  terraform/backend/s3/main.tf
  terraform/cluster/aws-eks/.terraform.lock.hcl
  terraform/cluster/talos/.terraform.lock.hcl
Labels: chore

#460 Fixes field is immutable issue when copying ca cert configmap
  kustomize/pki/resources/private-issuer/ca/copy-root-cert-job.yaml
Labels: bug

#459 Support bundles in CI
  .github/support-bundle.yaml
  .github/workflows/ci.yaml
  aqua.yaml
  contexts/local/blueprint.yaml
  contexts/local/terraform/cluster/talos.tfvars
Labels: chore

#461 Load br_netfilter in CI
  .github/workflows/ci.yaml
Labels: bug

#452 Wait and run terraform tests in parallel
  .github/workflows/ci.yaml
  Taskfile.yaml
  contexts/local/blueprint.yaml
  contexts/local/terraform/cluster/talos.tfvars
  docs/terraform/cluster/talos.md
  lefthook.yml
  terraform/cluster/talos/.terraform.lock.hcl
Labels: chore

#467 Add insecure metrics-server option
  kustomize/telemetry/resources/metrics-server/helm-release.yaml
  kustomize/telemetry/resources/metrics-server/skip-tls/kustomization.yaml
  kustomize/telemetry/resources/metrics-server/skip-tls/patches/helm-release.json
Labels: bug

#472 refactor(aks): Simplify identity management with system-assigned default
  docs/terraform/cluster/azure-aks.md
  terraform/cluster/azure-aks/main.tf
Labels: enhancement

#486 feat: add PVC/PV cleanup component
  kustomize/csi/cleanup/all-pvcs/deployment.yaml
  kustomize/csi/cleanup/all-pvcs/kustomization.yaml
  kustomize/csi/cleanup/all-pvcs/rbac.yaml
  kustomize/csi/cleanup/kustomization.yaml
Labels: feature

#488 Relocate terraform module docs
  Taskfile.yaml
  docs/terraform/cluster/azure-aks.md
  terraform/.terraform-docs.yml
  terraform/backend/azurerm/README.md
  terraform/backend/s3/README.md
  terraform/cluster/aws-eks/README.md
  terraform/cluster/azure-aks/README.md
  terraform/cluster/talos/README.md
  terraform/gitops/flux/README.md
  terraform/network/aws-vpc/README.md
  terraform/network/azure-vnet/README.md
Labels: chore

#502 feat(eks): enhance EKS cluster for improved lifecycle performance
  contexts/aws-example/blueprint.yaml
  contexts/aws-example/terraform/cluster/aws-eks.tfvars
  contexts/aws-example/terraform/gitops/flux.tfvars
  contexts/aws-example/terraform/network/aws-vpc.tfvars
  terraform/backend/s3/.terraform.lock.hcl
  terraform/backend/s3/main.tf
  terraform/cluster/aws-eks/.terraform.lock.hcl
  terraform/cluster/aws-eks/README.md
  terraform/cluster/aws-eks/main.tf
  terraform/cluster/aws-eks/outputs.tf
  terraform/cluster/aws-eks/templates/kubeconfig.tpl
  terraform/cluster/aws-eks/test.tftest.hcl
  terraform/cluster/aws-eks/variables.tf
  terraform/network/aws-vpc/.terraform.lock.hcl
  terraform/network/aws-vpc/README.md
  terraform/network/aws-vpc/main.tf
  terraform/network/aws-vpc/outputs.tf
  terraform/network/aws-vpc/test.tftest.hcl
  terraform/network/aws-vpc/variables.tf
  windsor.yaml
Labels: enhancement
