Repository windsorcli/core, pull requests merged in 2025-01, with the labels that each got.

#8 Update CI to comply with blueprint guidelines
  .github/renovate.json
  .github/workflows/ci.yaml
  LICENSE
Labels: enhancement

#37 Updated blueprint references
  .github/workflows/ci.yaml
Labels: enhancement

#56 Add nginx-ingress-controller
  .github/renovate.json
  contexts/local/Corefile
  contexts/local/blueprint.yaml
  contexts/local/compose.yaml
  contexts/local/terraform/cluster/talos.tfvars
  contexts/local/terraform/gitops/flux.tfvars
  kustomize/ingress/base/kustomization.yaml
  kustomize/ingress/base/namespace.yaml
  kustomize/ingress/base/nginx/helm-release.yaml
  kustomize/ingress/base/nginx/helm-repository.yaml
  kustomize/ingress/base/nginx/kustomization.yaml
  kustomize/ingress/base/nginx/nodeport/kustomization.yaml
  kustomize/ingress/base/nginx/nodeport/patches/helm-release.yaml
  windsor.yaml
Labels: feature

#66 Move to 'default' context
  contexts/default/blueprint.yaml
  contexts/default/terraform/cluster/talos.tfvars
  contexts/default/terraform/gitops/flux.tfvars
  windsor.yaml
Labels: chore

#68 Cert-manager with selfsigned cert
  contexts/default/blueprint.yaml
  contexts/default/terraform/cluster/talos.tfvars
  kustomize/ingress/base/nginx/nodeport-web/patches/helm-release.yaml
  kustomize/kustomization.yaml
  kustomize/pki/base/cert-manager/helm-release.yaml
  kustomize/pki/base/cert-manager/helm-repository.yaml
  kustomize/pki/base/cert-manager/kustomization.yaml
  kustomize/pki/base/kustomization.yaml
  kustomize/pki/base/namespace.yaml
  kustomize/pki/resources/issuer.yaml
  kustomize/pki/resources/kustomization.yaml
  kustomize/pki/resources/public-issuer/selfsigned/kustomization.yaml
  kustomize/pki/resources/public-issuer/selfsigned/patches/public-issuer.yaml
Labels: feature
